package com.ssmt.cli;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.Callable;
import picocli.CommandLine.Command;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.Option;
import picocli.CommandLine.Spec;

/** Observes one candidate and optional downloaded asset without inferring runtime or release rights. */
@Command(name = "release-chain", mixinStandardHelpOptions = true,
        description = "Report exact source-record, package, and separately supplied asset evidence.")
public final class ReleaseChainCommand implements Callable<Integer> {
    @Option(names = "--source-record", required = true,
            description = "release-source.txt generated by the release workflow.")
    private Path sourceRecord;
    @Option(names = "--archive", required = true) private Path archive;
    @Option(names = "--downloaded-asset",
            description = "An independently downloaded copy of this same release asset.")
    private Path downloadedAsset;
    @Spec private CommandSpec spec;

    @Override public Integer call() {
        try {
            Map<String, String> source = new LinkedHashMap<>();
            for (String line : Files.readAllLines(sourceRecord)) {
                int delimiter = line.indexOf('=');
                if (delimiter > 0) { source.put(line.substring(0, delimiter), line.substring(delimiter + 1)); }
            }
            String commit = source.getOrDefault("commit", "");
            String version = source.getOrDefault("version", "");
            String archiveHash = sha256(archive);
            String downloadedHash = downloadedAsset == null ? null : sha256(downloadedAsset);
            String sourceState = commit.matches("[0-9a-fA-F]{40}") && !version.isBlank()
                    ? "OBSERVED_RECORD" : "UNKNOWN";
            String publicationState = downloadedHash == null ? "NOT_RUN"
                    : archiveHash.equals(downloadedHash) ? "ASSET_BYTES_MATCH" : "FAIL";
            Map<String, Object> report = new LinkedHashMap<>();
            report.put("schemaVersion", "ssmt-release-chain-1");
            report.put("sourceRecord", Map.of("state", sourceState, "commit", commit,
                    "version", version, "sha256", sha256(sourceRecord)));
            report.put("package", Map.of("state", "PASS", "filename", java.util.Objects.requireNonNull(archive.getFileName()).toString(),
                    "bytes", Files.size(archive), "sha256", archiveHash));
            report.put("downloadedAsset", Map.of("state", publicationState,
                    "sha256", downloadedHash == null ? "" : downloadedHash));
            report.put("gates", Map.of("offline", "UNKNOWN", "native", "UNKNOWN",
                    "live", "UNKNOWN", "rights", "UNKNOWN", "publication",
                    publicationState.equals("FAIL") ? "FAIL" : "UNKNOWN"));
            report.put("limitations", java.util.List.of(
                    "Source record content and remote asset origin are not independently authenticated",
                    "Package byte identity does not establish native or live behavior"));
            spec.commandLine().getOut().println(new ObjectMapper().writeValueAsString(report));
            return sourceState.equals("OBSERVED_RECORD") && !publicationState.equals("FAIL") ? 0 : 1;
        } catch (IOException exception) {
            spec.commandLine().getErr().println("Release-chain check failed: " + exception.getMessage());
            return 1;
        }
    }

    private static String sha256(Path path) throws IOException {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(path)));
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 unavailable", exception);
        }
    }
}
